# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bd47ea3a325c72c6f7f5b373000a35894294bea6cc92cdc3f0d90f75a58452d0310871ef91b5da83a05a52850783863edfe13a3c4a68f9eaa8b8692ba7a0b6a

test:
  secret_key_base: a43104205a50e75740318f53c9f61002d39bbfe91f8bc0db3bdee129a5a1ee5ffbb5e44654763e791638817bc94938a74616c91227b297cff993609c491cf311

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
